name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Jalan setiap jam 12 malam
  workflow_dispatch: # Supaya bisa run manual

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # Kita simpan di folder profile biar rapi
          outputs: profile/snake.svg?palette=github-dark

      - name: Push to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/snake.svg
          git commit -m "Update snake" || exit 0
          git push